
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: medusa-backup-client
  namespace: medusa-operator
rules:
- apiGroups:
  - cassandra.k8ssandra.io
  resources:
  - cassandrabackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cassandra.k8ssandra.io
  resources:
  - cassandrabackups/status
  verbs:
  - get
  - patch
  - update

