apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: medusa-backup-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: medusa-backup-client
subjects:
  - kind: ServiceAccount
    name: medusa-backup-client
