# permissions for end users to view cassandrarestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cassandrarestore-viewer-role
rules:
- apiGroups:
  - cassandra.k8ssandra.io
  resources:
  - cassandrarestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cassandra.k8ssandra.io
  resources:
  - cassandrarestores/status
  verbs:
  - get
